<form class="form contact" action="<?= $block->getFormUrl() ?>" id="contact-form" method="post" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="name">Name</label>
            <div class="control">
                <input name="name" id="name"  value="" class="input-text" type="text" data-validate="{required:true}" placeholder="Name"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email">Email from</label>
            <div class="control">
                <input name="email" id="email" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="From"/>
            </div>
        </div>
        <div class="field subject required">
            <label class="label" for="subject">Subject</label>
            <div class="control">
                <input name="subject" id="subject" class="input-text" type="text" data-validate="{required:true}" placeholder="Subject"/>
            </div>
        </div>
        <div class="field message required">
            <label class="label" for="message">Message</label>
            <div class="control">
                <textarea name="message" id="message" class="input-text" cols="5" rows="3" data-validate="{required:true}" placeholder="Message"></textarea>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary">
                    <span>Submit</span>
                </button>
            </div>
        </div>
    </fieldset>
</form>